import type { Metadata } from "next";
import { Lato,Nunito, Montserrat } from "next/font/google";
import "./globals.css";

import { Roboto_Mono } from 'next/font/google'
 
const nuni = Nunito({
  subsets: ['latin'],
  variable: '--font-nuni',
  display: 'swap',
})
 
const lato = Lato({
  weight: ['100','300','400','900', '700'],
  subsets: ['latin'],
  variable: '--font-lato',
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${nuni.variable} ${lato.variable}`}>
      <body>{children}</body>
    </html>
  );
}
